const langEN = {
    appTitle: 'Find your favorite pet',
    appUnderTitle: `web application that allows users to store and manage their contacts,
    providing features for adding, editing, and deleting contact information`,
    homeBtn: 'Home',

    news: 'News',
    find: 'Find pet',
    findPet: 'Find your favorite pet',
    friends: 'Our Friends',
    contactsBtn: 'Contacts',
    logBtn: 'Login',
    regBtn: 'Register',
    footerTitle: 'React-Phonebook-2023',
    name: 'Name',
    sname: "name",
    email: 'Email',
    pass: 'Password',
    regSubmit: "SignUp",
    logSubmit: "SignIn",
    alreadyGot: "Already have an account?",
    notYet: "Don't have an account?",
    show: "Show",
    hide: "Hide",
    left: "seconds left",
    wasted: "Wasted",
    try: "Try again",
    phonebook: "Phonebook",
    number: "Number",
    phone: "phone",
    
    empty: "List is empty ...",
    add: "Add contact",
    edit: "EDIT",
    delete: "DELETE",
    avatar: "Avatar",
    set: "Set",
    settings: "Settings",
    out: "LogOut",
    sorry: "Sorry dude, we couldn't find that page",
    
    
}


const langUA = {
    appTitle: 'Знайдіть свого улюбленого вихованця',
    appUnderTitle: `веб додаток, який дозволяє користувачам зберігати та керувати своїми контактами,
    надання функцій для додавання, редагування та видалення контактної інформації`,
    homeBtn: 'Головна',

    news: 'Новини',
    find: 'Знайдіть улюбленця',
    findPet: 'Знайдіть улюбленого вихованця',
    friends: 'Наші друзі',
    contactsBtn: 'Контакти',
    logBtn: 'Увійти',
    regBtn: 'Реєстрація',
    footerTitle: 'React-телефонна книга-2023',
    name: 'Ім’я',
    sname: "ім’я",
    email: 'Пошта',
    pass: 'Пароль',
    regSubmit: "Зареєструватися",
    logSubmit: "Увійти",
    alreadyGot: "Вже є акаунт?",
    notYet: "Немає акаунту?",
    show: "Показати",
    hide: "Приховати",
    left: "секунд залишилося",
    wasted: "Витрачено",
    try: "Спробуйте знову",
    phonebook: "Телефонна книга",
    number: "Номер",
    phone: "номер",
    
    empty: "Список порожній...",
    add: "Додати контакт",
    edit: "РЕДАГУВАТИ",
    delete: "ВИДАЛИТИ",
    avatar: "Аватар",
    set: "Встановити",
    settings: "Налаштування",
    out: "Вийти",
    sorry: "Вибач чувак, ми не змогли знайти цю сторінку",

}

export { langEN, langUA} // {lang.homeBtn}